stages:
  - test

.variables_template: &variables_definition
  variables:
    BASE_NAME: "mapper.lv2"
    PKG_CONFIG_PATH: "/opt/lv2/lib/pkgconfig:/opt/${CI_BUILD_NAME}/lib/pkgconfig:/usr/lib/${CI_BUILD_NAME}/pkgconfig"

.common_template: &common_definition
  <<: *variables_definition
  stage: test 

.build_template: &build_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build

.test_template: &test_definition
  <<: *common_definition
  script:
    - meson --cross-file "${CI_BUILD_NAME}" build
    - ninja -C build
    - cd build
    - meson test --verbose --wrap "${CI_BUILD_NAME}.wrap"

.universal_linux_template: &universal_linux_definition
  image: ventosus/universal-linux-gnu
  <<: *test_definition

.arm_linux_template: &arm_linux_definition
  image: ventosus/arm-linux-gnueabihf
  <<: *test_definition

.universal_w64_template: &universal_w64_definition
  image: ventosus/universal-w64-mingw32
  before_script:
    - ln -s /usr/i686-w64-mingw32/lib/libwinpthread-1.dll /opt/i686-w64-mingw32/lib/libwinpthread-1.dll
    - ln -s /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll /opt/x86_64-w64-mingw32/lib/libwinpthread-1.dll
  <<: *test_definition

.universal_apple_template: &universal_apple_definition
  image: ventosus/universal-apple-darwin
  <<: *build_definition

# building in docker
x86_64-linux-gnu:
  <<: *universal_linux_definition

i686-linux-gnu:
  <<: *universal_linux_definition

arm-linux-gnueabihf:
  <<: *arm_linux_definition

aarch64-linux-gnu:
  <<: *arm_linux_definition

x86_64-w64-mingw32:
  <<: *universal_w64_definition

i686-w64-mingw32:
  <<: *universal_w64_definition

universal-apple-darwin:
  <<: *universal_apple_definition
